#:schema https://mise.jdx.dev/schema/mise.json

[tools]
# core tools
node = "latest"
python = "latest"
uv = "latest"
bun = "latest"

# provides completion and parsing support for tasks see:
# https://mise.jdx.dev/tasks/file-tasks.html#arguments
usage = "latest"

# useful global tools
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:mcp-hub" = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"npm:sort-package-json" = "latest"
"npm:ccstatusline" = "latest"

[settings]
# experimental = true
legacy_version_file = true
idiomatic_version_file_enable_tools = ['node']
always_keep_download = false                       # deleted after install by default
always_keep_install = false                        # deleted on failure by default
disable_default_shorthands = false                 # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
env_file = '.env'
http_timeout = "30"                                # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
jobs = 16                                          # number of plugins to install in parallel. The default is `4`.
not_found_auto_install = true                      # see MISE_NOT_FOUND_AUTO_INSTALL
paranoid = false                                   # see MISE_PARANOID
plugin_autoupdate_last_check_duration = '1 day'    # set to 0 to disable updates
raw = false                                        # set to true to directly pipe plugins to stdin/stdout/stderr
shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
task_output = "prefix"                             # see Tasks Runner for more information
verbose = false                                    # set to true to see full installation output, see `MISE_VERBOSE`
yes = true                                         # set to true to automatically answer yes to all prompts

[settings.python]
# use precompiled binaries instead of building Python from source
# precompiled binaries are supported by Astral
# https://github.com/astral-sh/python-build-standalone
# https://mise.jdx.dev/lang/python.html#precompiled-python-binaries
compile = false

[settings.pipx]
# https://mise.jdx.dev/dev-tools/backends/pipx.html
# use uvx instead of pipx
uvx = true
